### ISSUE TITLE
How to add phone skin in emulator?

### ISSUE THREAD

**Issue by premkumar5012002** [google/android-emulator-m1-preview#11]
Hello, is there any way to add phone skins on emulator in m1 preview on android studio Canary build.

**Comment by 741g** [comment]
Hi, phone graphical skins are not supported in the M1 version of the emulator, but resolution and dpi should still reflect what the phone skin specifies. You can check `ANDROID_SDK_ROOT/skins` for how skins are defined and add your own there.
