### ISSUE TITLE
How to connect with react native?

### ISSUE THREAD

**Issue by quadrixm** [google/android-emulator-m1-preview#13]
I am trying to run prerelease 3 for a react native project but it's not detecting the emulator. I have started the emulator. 

Running command `adb devices` show this result
```
List of devices attached
emulator-5554	device
```

But when I run `emulator -list-avds` it's not showing there

**Comment by radko93** [comment]
I'm using it with react native. If it's the only device you have connected react native should choose this one?

**Comment by quadrixm** [comment]
It's working now 👍. Previously I had set up an emulator on android studio, but then I removed it and restart the system and run it and it worked.
