### ISSUE TITLE
How can I change to the tablet size(height : 1280, width : 800, dpi : 216)?

### ISSUE THREAD

**Issue by st2222** [google/android-emulator-m1-preview#24]
How can I change the emulator size to the tablet size(height : 1280, width : 800, dpi : 216)?
When I changed the emulator to the tablet size(height : 1280, width : 800, dpi : 216) in config.ini, it did not work.

**Comment by bongio94** [comment]
> How can I change the emulator size to the tablet size(height : 1280, width : 800, dpi : 216)?
> When I changed the emulator to the tablet size(height : 1280, width : 800, dpi : 216) in config.ini, it did not work.

This is what you are looking for https://github.com/google/android-emulator-m1-preview#how-to-configure

**Comment by bongio94** [comment]
> How can I change the emulator size to the tablet size(height : 1280, width : 800, dpi : 216)?
> When I changed the emulator to the tablet size(height : 1280, width : 800, dpi : 216) in config.ini, it did not work.

I also faced this issue while changing the display size. When I change the dpi setting the emulator won't start. If I leave the dpi to his default value it works with the new height/width

**Comment by st2222** [comment]
Thank you, however I have to change the dpi.
I suppose there are no way to solve this issue now.
