### ISSUE TITLE
Could not automatically detect an ADB Binary

### ISSUE THREAD

**Issue by mydudechris** [google/android-emulator-m1-preview#26]
- Installed latest release on Mac Mini M1 running 11.2.2
- Android Studio 4.1.2 is installed and adb runs in terminal (path recognized)
- Running latest release of preview, on open, get "Could not automatically detect an ADB binary.Some emulator func...'Use detected ADB location'
- I cannot find that setting in my Android studio prefs
- The preview appears to run however this error pops up, thought I should report it

**Comment by Yes-In** [comment]
In emulator menu (3 points), select Settings (almost bottom) and on General tab in right column second switch "Use detected ADB location"

**Comment by mydudechris** [comment]
Ah, got it. Thanks
