### ISSUE TITLE
Setting ADB path causes spinning pinwheel of death

### ISSUE THREAD

**Issue by PlanetWilson** [google/android-emulator-m1-preview#3]
I hadn't downloaded ADB so it didn't detect a location, once I had downloaded just ADB I couldn't then manually select a location as it pinwheels and I have to kill the app. It isn't possible to simply type into the path box either.

M1 MacBook Air, 16GB / 512GB, macOS 11.1

**Comment by 741g** [comment]
Hi, this should be fixed in the current preview.

**Comment by PlanetWilson** [comment]
Confirmed working thanks
