### ISSUE TITLE
How to get it in Android Studio SDK Manager?

### ISSUE THREAD

**Issue by xiaokang00010** [google/android-emulator-m1-preview#30]
I noticed this sentence in the README

- Support for downloading the M1-based emulator was added to SDK Manager, so it's not necessary to go to the Github releases page to download a standalone .app anymore. In AVD Manager go to the Other Images tab as by default it doesn't show the ARM64 images.

I downloaded Android Studio but It can only be translated by Rosetta.
And when I try to install AVD in Android Studio , It will prompt "The device does not support VT-x"

**Comment by hannesa2** [comment]
Ignore the message and use one of them 
![image](https://user-images.githubusercontent.com/3314607/111005083-71a07a00-838a-11eb-9c69-bde316cd12e4.png)

**Comment by xiaokang00010** [comment]
Thanks for your reply

**Comment by anoop4real** [comment]
> Ignore the message and use one of them
> ![image](https://user-images.githubusercontent.com/3314607/111005083-71a07a00-838a-11eb-9c69-bde316cd12e4.png)

Hi I am using the latest Android studio,  i am not getting this option under "Other Images".

**Comment by ndreisg** [comment]
Same here, I don't see API Level 30 images, only images until API Level 25 and S

**Comment by alearcy** [comment]
Same here. I only see 25 and S images, no 30.

**Comment by danielgindi** [comment]
You have to install SDK Platform Tools for v30.

**Comment by ryansgot** [comment]
@danielgindi 

I, too, noticed that I do not have access to an API 30 arm64-v8a emulator. For example:
```
Ryans-MBP:bin ryan$ ./sdkmanager --list | grep arm64
  system-images;android-24;default;arm64-v8a                                               | 7            | ARM 64 v8a System Image                                             
  system-images;android-24;google_apis;arm64-v8a                                           | 27           | Google APIs ARM 64 v8a System Image                                 
  system-images;android-25;google_apis;arm64-v8a                                           | 18           | Google APIs ARM 64 v8a System Image                                 
  system-images;android-S;google_apis;arm64-v8a                                            | 4            | Google APIs ARM 64 v8a System Image                                 
  system-images;android-S;google_apis_playstore;arm64-v8a                                  | 4            | Google Play ARM 64 v8a System Image 
  ```

I'm only able to find links to install sdk platform tools for r31, but I would really like to create an arm64-v8a emulator at API 30
```
Ryans-MBP:tmp ryan$ wget -v https://dl.google.com/android/repository/platform-tools-latest-darwin.zip
--2021-05-31 12:34:17--  https://dl.google.com/android/repository/platform-tools-latest-darwin.zip
Resolving dl.google.com (dl.google.com)... 142.251.33.110
Connecting to dl.google.com (dl.google.com)|142.251.33.110|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dl.google.com/android/repository/42b081e1e068bb936179551684cdcb30315e245c.platform-tools_r31.0.2-darwin.zip [following]
--2021-05-31 12:34:18--  https://dl.google.com/android/repository/42b081e1e068bb936179551684cdcb30315e245c.platform-tools_r31.0.2-darwin.zip
Reusing existing connection to dl.google.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 13829393 (13M) [application/zip]
Saving to: ‘platform-tools-latest-darwin.zip’
```

If I attempt to use convention to construct the URL . . . 
```
Ryans-MBP:tmp ryan$ wget https://dl.google.com/android/repository/platform-tools-r30.0.5-darwin.zip
--2021-05-31 12:42:32--  https://dl.google.com/android/repository/platform-tools-r30.0.5-darwin.zip
Resolving dl.google.com (dl.google.com)... 142.251.33.110
Connecting to dl.google.com (dl.google.com)|142.251.33.110|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-05-31 12:42:32 ERROR 404: Not Found.
```

Do you know what the link is for this version?

**Comment by ndreisg** [comment]
> You have to install SDK Platform Tools for v30.

There are no SDK platform tools "for" v30. Latest version of SDK platform tools are 31.0.2 (which I have installed) and they are backwards compatible with older Android versions.

If you mean we have to install the v30 SDK: I have it installed but I still don't see the arm64 emulators.

**Comment by ndreisg** [comment]
I was able to find the arm64 emulators after I installed Android Studio Arctic Fox Beta 5 from https://developer.android.com/studio/preview
