### ISSUE TITLE
Cannot install the emulator from the AVD Manager on M1

### ISSUE THREAD

**Issue by usoliveira** [google/android-emulator-m1-preview#31]
A few days ago, you updated the README saying that now its possible to install de M1 emulator directly from the AVD, including that it will not show ARM64 image versions anymore... but I can't find it. I'm using Android Studio 4.2 Preview (once the stable version sometimes freeze to me), but can't make the emulator work without downloading it from here.

Can you describe it better how to make it work? Which version of Android Studio are you using?

Thanks a lot!

**Comment by hannesa2** [comment]
I did this https://github.com/741g/android-emulator-m1-preview/issues/10#issuecomment-773545412 but maybe it's no more necessary

**Comment by ZeroPie** [comment]
can confirm
as of 4.2 its not possible
![Screenshot 2021-03-15 at 12 07 50](https://user-images.githubusercontent.com/8741666/111200269-2a330d00-8587-11eb-83c7-3ee8837377a8.png)

**Comment by mununki** [comment]
I have a same issue. Is there any guide or documentation to install the emulator for m1?

**Comment by loyio** [comment]
same issue

**Comment by cerradosoftware** [comment]
same issue

**Comment by mtzrmzia** [comment]
same here

**Comment by russeg** [comment]
The documentation is wrong. Someone made a pull request (without testing) based on a comment on Reddit (that I can't find) that it should work (obviously not, see the above comments) and pull was accepted (without checking if said comment actually works).

Anyway, just download the old dmg. It still works for very basic stuff.

**Comment by ZeroPie** [comment]
It does work but it has to be the preview Version of Android Studio:

![Screenshot 2021-03-24 at 07 41 44](https://user-images.githubusercontent.com/8741666/112320310-87f4e280-8c74-11eb-9687-102989f6c766.png)

**Comment by halilozel1903** [comment]
Hi, if you follow this blog post. You can install and use an emulator on your M1 device. 

https://medium.com/techiepedia/setting-up-android-emulator-in-m1-mac-fff58ec8bff8

**Comment by VanilsonFernandes** [comment]
> It does work but it has to be the preview Version of Android Studio:
> 
> ![Screenshot 2021-03-24 at 07 41 44](https://user-images.githubusercontent.com/8741666/112320310-87f4e280-8c74-11eb-9687-102989f6c766.png)

it worked for me

**Comment by usoliveira** [comment]
Confirmed! It has to be the **Preview version of Android Studio**! Than, when you look at "Other images" tab, choosing an "arm64-v*"will work for running your android emulator! Thanks to all.

**Comment by xuduo** [comment]
> Confirmed! It has to be the **Preview version of Android Studio**! Than, when you look at "Other images" tab, choosing an "arm64-v*"will work for running your android emulator! Thanks to all.

Which android studio version and emulator version did you use?
Mine is 4.2 beta 6 and 30.6.1 which does not work.

**Comment by bhandaribhuminpfizer** [comment]
Not able to see "arm64-v8A* for Android 11  on "Other images" tab
![Screenshot 2021-05-14 at 12 05 21 PM](https://user-images.githubusercontent.com/79249987/118231470-d07a9080-b4ac-11eb-86a2-e580ed0e4523.png)
