### ISSUE TITLE
Cant run emulator ARM64

### ISSUE THREAD

**Issue by lukaskris** [google/android-emulator-m1-preview#34]
<img width="939" alt="image" src="https://user-images.githubusercontent.com/15793303/111597790-20b4d980-8801-11eb-96b7-a4b7cb1fa9dd.png">

do you have another solution for this issue?

**Comment by hannesa2** [comment]
Start it from command line, then you will see the reason

**Comment by lukaskris** [comment]
I got the error message

Could not launch '/Users/lukaskris/Library/Android/sdk/emulator/qemu/darwin-x86_64/qemu-system-aarch64': No such file or 
directory

**Comment by hannesa2** [comment]
`darwin-x86_64`

**Comment by lukaskris** [comment]
Where I can change the config with darwin-aarch64?

**Comment by lukaskris** [comment]
already fixed. just re run darwin-aarch64-replace.sh and everything fine
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15793303/111617218-6d0a1480-8815-11eb-8843-42ccad82868a.png">


thanks

**Comment by hannesa2** [comment]
If a Google engineer reads this, I can tell it's confusing and error prone !

I found the script here 
`./Library/Android/sdk/emulator/darwin-aarch64-replace.sh` and here
`/Applications/Android\ Emulator.app/Contents/MacOS/emulator/darwin-aarch64-replace.sh`
 
When I run it , I see `emulator-darwin-aarch64-0.2-engine-only.zip` but **0.3** is out, but without this script.
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/3314607/111661194-1ac5f500-880f-11eb-9cb8-8ed24ed176e4.png">

At the end I see an error

`rm: ./qemu-img: No such file or directory`

And now it stops working  ...
<img width="445" alt="image" src="https://user-images.githubusercontent.com/3314607/111661465-5496fb80-880f-11eb-877d-3ee66bb9a5fa.png">

🙈

**Comment by hannesa2** [comment]
Good news, this is still working 
<img width="159" alt="image" src="https://user-images.githubusercontent.com/3314607/111662271-10f0c180-8810-11eb-999a-75b31dc40877.png">

**Comment by lukaskris** [comment]
Yes in the end I had some error 
./qemu-img: No such file or directory

but I try moved all file at .zip to the root folder (Library/Android/sdk/emulator/)

and then quit the android studio, try to reopen from AVD and first of all no error message again. and just run my emulator normally like the old macbook.

<img width="210" alt="image" src="https://user-images.githubusercontent.com/15793303/111723330-ee08f080-8895-11eb-855a-1f0d4405da4c.png">

**Comment by morlay** [comment]
@lukaskris 
same issue when first installed. see https://github.com/google/android-emulator-m1-preview/issues/1#issuecomment-818398763

**Comment by Shaikh-Aabid** [comment]
> already fixed. just re run darwin-aarch64-replace.sh and everything fine <img alt="image" width="1440" src="https://user-images.githubusercontent.com/15793303/111617218-6d0a1480-8815-11eb-8843-42ccad82868a.png">
> 
> thanks

how to do it ?

**Comment by abcdsxg** [comment]
> > already fixed. just re run darwin-aarch64-replace.sh and everything fine <img alt="image" width="1440" src="https://user-images.githubusercontent.com/15793303/111617218-6d0a1480-8815-11eb-8843-42ccad82868a.png">
> > thanks
> 
> how to do it ?

Download the https://github.com/google/android-emulator-m1-preview/releases/download/0.2/emulator-darwin-aarch64-0.2-engine-only.zip

unzip it

replace `emulator` and `emulator-check` to  `~/Library/Android/sdk/tools/`

now you can run  emulator from shell

**Comment by benomatis** [comment]
> Download the https://github.com/google/android-emulator-m1-preview/releases/download/0.2/emulator-darwin-aarch64-0.2-engine-only.zip
> 
> unzip it
> 
> replace `emulator` and `emulator-check` to `~/Library/Android/sdk/tools/`
> 
> now you can run emulator from shell

What I did differently is that once unzipping the downloaded emulator from that link (which is version 30.9.4), is that I first uninstalled the emulator (I had 31) via SDK Manager > SDK Tools (this effectively removed the `emulator` folder from `~/Library/Android/sdk/`), then renamed the unzipped folder to `emulator` and moved it inside the `~/Library/Android/sdk/` folder - it is now showing up properly as the installed emulator with version 30.9.4 and I can now start the emulator fine.

**Comment by Shaikh-Aabid** [comment]
> 

Thank you so much my issue is fixed :)

**Comment by sergtimosh** [comment]
I had 2 emulator binaries, and one was in the ~/Library/Android/sdk/tools/
If the above steps doesn't help you, try to delete **tools** folder or particularly it's emulator binary.
![image](https://user-images.githubusercontent.com/26712442/145575647-a196d677-7dad-4ac8-b5a4-6c2e863d63e2.png)

**Comment by samstorino** [comment]
Reinstalling the "Android Emulator" via **Tools -> SDK Manager > SDK Tools** tab solved the issue for me.

Why? I originally downloaded an old version of Android Studio that wasn't compatible with the M1 macbook. This came with an old incompatible version of the "Android Emulator". I later upgraded to the latest version of Android Studio (Bumblebee) and attempted to run a pre-existing virtual device which showed the above error. I saw in the **Help -> Show Log in Finder -> idea.log** file that Android Studio was trying to replace the emulator I had installed on disk by running a shell script (darwin-aarch64-replace.sh). but it couldn't find that. This led me to believe the emulator itself was a problem, so I uninstalled then installed it again, triggering Android Studio to download a M1 compatible version.

**Comment by maurice-ellis** [comment]
@samstorino Thank you, spent all day trying to fix this emulator, uninstalled and reinstalled, now everything works great.

**Comment by Guang1234567** [comment]
> I had 2 emulator binaries, and one was in the ~/Library/Android/sdk/tools/ If the above steps doesn't help you, try to delete **tools** folder or particularly it's emulator binary. ![image](https://user-images.githubusercontent.com/26712442/145575647-a196d677-7dad-4ac8-b5a4-6c2e863d63e2.png)

As memtion of above quote

Just copy `emulator` and  `emulator-check` from `emulator dir` to `tools dir`, then overwrite.  

Everything is ok... 

@sergtimosh  @samstorino @maurice-ellis

**Comment by Guang1234567** [comment]
My commandline to launch emlator on macos m1 aarch64

```
$ which emulator

/Users/xxxx/dev_kit/sdk/android_sdk/tools/emulator


$ emulator -list-avds

Android_TV_1080p_API_31


$emulator -avd Android_TV_1080p_API_31 -netdelay none -netspeed full

INFO    | Android emulator version 31.3.10.0 (build_id 8807927) (CL:N/A)
emulator: INFO: Found systemPath /Users/lihanguang/dev_kit/sdk/android_sdk/system-images/android-31/android-tv/arm64-v8a/
INFO    | Duplicate loglines will be removed, if you wish to see each indiviudal line launch with the -log-nofilter flag.
WARNING | unexpected system image feature string, emulator might not function correctly, please try updating the emulator.
INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_new_posture_requested(int) ((null):0, (null))
# ....
# ....
```

![image](https://user-images.githubusercontent.com/8240718/185878480-b95f8c6b-632d-4077-86fe-6ea2b9cc38b5.png)

**Comment by geilige** [comment]
I failed on the ubuntu 20.04 arm64 system. The error is as follows

root@ubuntu:~/Android/Sdk/emulator# ./darwin-aarch64-replace.sh 
curl -L https://github.com/google/android-emulator-m1-preview/releases/download/0.2/emulator-darwin-aarch64-0.2-engine-only.zip -o emulator-darwin-aarch64-0.2.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 91.8M  100 91.8M    0     0  8034k      0  0:00:11  0:00:11 --:--:-- 7943k
unzip emulator-darwin-aarch64-0.2.zip
Archive:  emulator-darwin-aarch64-0.2.zip
   creating: emulator-darwin-aarch64-0.2/
  inflating: emulator-darwin-aarch64-0.2/NOTICE.csv  
  inflating: emulator-darwin-aarch64-0.2/qsn  
  inflating: emulator-darwin-aarch64-0.2/qemu-img  
   creating: emulator-darwin-aarch64-0.2/lib64/
  inflating: emulator-darwin-aarch64-0.2/lib64/libemugl_common.dylib  
   creating: emulator-darwin-aarch64-0.2/lib64/qt/
   creating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/
   creating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/platforms/
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/platforms/libqcocoa.dylib  
   creating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/styles/
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/styles/libqmacstyle.dylib  
   creating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/bearer/
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/bearer/libqgenericbearer.dylib  
   creating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/iconengines/
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/iconengines/libqsvgicon.dylib  
   creating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/imageformats/
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/imageformats/libqgif.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/imageformats/libqwbmp.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/imageformats/libqwebp.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/imageformats/libqico.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/imageformats/libqmacheif.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/imageformats/libqjpeg.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/imageformats/libqtiff.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/imageformats/libqsvg.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/imageformats/libqicns.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/imageformats/libqtga.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/plugins/imageformats/libqmacjp2.dylib  
   creating: emulator-darwin-aarch64-0.2/lib64/qt/lib/
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/lib/libQt5CoreAndroidEmu.5.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/lib/libQt5PrintSupportAndroidEmu.5.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/lib/libQt5SvgAndroidEmu.5.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/lib/libQt5WidgetsAndroidEmu.5.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/lib/libQt5DBusAndroidEmu.5.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/lib/libQt5GuiAndroidEmu.5.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/qt/lib/libQt5NetworkAndroidEmu.5.dylib  
   creating: emulator-darwin-aarch64-0.2/lib64/gles_swiftshader/
  inflating: emulator-darwin-aarch64-0.2/lib64/gles_swiftshader/libEGL.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/gles_swiftshader/libGLES_CM.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/gles_swiftshader/libGLESv2.dylib  
   creating: emulator-darwin-aarch64-0.2/lib64/vulkan/
  inflating: emulator-darwin-aarch64-0.2/lib64/vulkan/libMoltenVK.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/vulkan/MoltenVK_icd.json  
  inflating: emulator-darwin-aarch64-0.2/lib64/libshadertranslator.dylib  
  inflating: emulator-darwin-aarch64-0.2/lib64/libOpenglRender.dylib  
  inflating: emulator-darwin-aarch64-0.2/LICENSE  
  inflating: emulator-darwin-aarch64-0.2/darwin-aarch64-replace.sh  
   creating: emulator-darwin-aarch64-0.2/resources/
   creating: emulator-darwin-aarch64-0.2/resources/macroPreviews/
  inflating: emulator-darwin-aarch64-0.2/resources/macroPreviews/Reset_position.mp4  
  inflating: emulator-darwin-aarch64-0.2/resources/macroPreviews/Walk_to_image_room.mp4  
  inflating: emulator-darwin-aarch64-0.2/resources/macroPreviews/Track_vertical_plane.mp4  
  inflating: emulator-darwin-aarch64-0.2/resources/macroPreviews/Track_horizontal_plane.mp4  
  inflating: emulator-darwin-aarch64-0.2/resources/Toren1BD_Decor.png  
  inflating: emulator-darwin-aarch64-0.2/resources/poster.png  
  inflating: emulator-darwin-aarch64-0.2/resources/Toren1BD.mtl  
  inflating: emulator-darwin-aarch64-0.2/resources/Toren1BD_Main.png  
  inflating: emulator-darwin-aarch64-0.2/resources/Toren1BD.posters  
  inflating: emulator-darwin-aarch64-0.2/resources/Toren1BD.obj  
   creating: emulator-darwin-aarch64-0.2/resources/macros/
  inflating: emulator-darwin-aarch64-0.2/resources/macros/Track_vertical_plane  
  inflating: emulator-darwin-aarch64-0.2/resources/macros/Reset_position  
  inflating: emulator-darwin-aarch64-0.2/resources/macros/Track_horizontal_plane  
  inflating: emulator-darwin-aarch64-0.2/resources/macros/Walk_to_image_room  
   creating: emulator-darwin-aarch64-0.2/bin64/
  inflating: emulator-darwin-aarch64-0.2/bin64/fsck.ext4  
  inflating: emulator-darwin-aarch64-0.2/bin64/mkfs.ext4  
  inflating: emulator-darwin-aarch64-0.2/bin64/tune2fs  
  inflating: emulator-darwin-aarch64-0.2/bin64/resize2fs  
  inflating: emulator-darwin-aarch64-0.2/bin64/e2fsck  
  inflating: emulator-darwin-aarch64-0.2/source.properties  
  inflating: emulator-darwin-aarch64-0.2/emulator-check  
  inflating: emulator-darwin-aarch64-0.2/NOTICE.txt  
  inflating: emulator-darwin-aarch64-0.2/android-info.txt  
  inflating: emulator-darwin-aarch64-0.2/perfetto-protozero-protoc-plugin  
   creating: emulator-darwin-aarch64-0.2/qemu/
   creating: emulator-darwin-aarch64-0.2/qemu/darwin-aarch64/
  inflating: emulator-darwin-aarch64-0.2/qemu/darwin-aarch64/qemu-system-aarch64  
  inflating: emulator-darwin-aarch64-0.2/qemu/darwin-aarch64/qemu-system-aarch64-headless  
  inflating: emulator-darwin-aarch64-0.2/mksdcard  
   creating: emulator-darwin-aarch64-0.2/lib/
  inflating: emulator-darwin-aarch64-0.2/lib/waterfall.proto  
  inflating: emulator-darwin-aarch64-0.2/lib/emulator_controller.proto  
  inflating: emulator-darwin-aarch64-0.2/lib/advancedFeaturesCanary.ini  
  inflating: emulator-darwin-aarch64-0.2/lib/hardware-properties.ini  
  inflating: emulator-darwin-aarch64-0.2/lib/advancedFeatures.ini  
  inflating: emulator-darwin-aarch64-0.2/lib/hostapd.conf  
   creating: emulator-darwin-aarch64-0.2/lib/pc-bios/
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/efi-e1000.rom  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/kvmvapic.bin  
   creating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/sl  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/pl  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/modifiers  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/sv  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/da  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/no  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/Makefile  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/ja  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/lv  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/it  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/is  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/cz  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/ru  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/en-gb  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/bepo  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/common  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/pt  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/fr-ch  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/fr-ca  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/mk  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/ar  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/hr  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/pt-br  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/hu  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/nl  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/de  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/fi  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/fr  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/es  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/et  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/lt  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/fo  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/en-us  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/de-ch  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/th  
 extracting: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/nl-be  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/fr-be  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/keymaps/tr  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/multiboot.bin  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/vgabios-stdvga.bin  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/bios.bin  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/vgabios-virtio.bin  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/bios-256k.bin  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/linuxboot_dma.bin  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/linuxboot.bin  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/efi-virtio.rom  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/efi-e1000e.rom  
  inflating: emulator-darwin-aarch64-0.2/lib/pc-bios/vgabios-cirrus.bin  
  inflating: emulator-darwin-aarch64-0.2/lib/snapshot_service.proto  
  inflating: emulator-darwin-aarch64-0.2/lib/emu-original-feature-flags.protobuf  
  inflating: emulator-darwin-aarch64-0.2/lib/snapshot.proto  
  inflating: emulator-darwin-aarch64-0.2/lib/ca-bundle.pem  
  inflating: emulator-darwin-aarch64-0.2/lib/ui_controller_service.proto  
  inflating: emulator-darwin-aarch64-0.2/emulator  
rm: 无法删除 './qsn': 没有那个文件或目录
