### ISSUE TITLE
Android studio arm64 emulator shows nothing but a black screen

### ISSUE THREAD

**Issue by jkw-statsig** [google/android-emulator-m1-preview#42]
It sounds like creating a AVD with arm64 image from Android Studio would work, but it's showing me nothing but a black screen. I tried different arm64 images (Nougat, S) as well as devices and got the same problem for them all. Also tried wiping data, changing emulated performance options.

![image](https://user-images.githubusercontent.com/77478330/113918677-91fc0280-9797-11eb-8868-f1581df06986.png)

**Comment by jkw-statsig** [comment]
Just as I posted the issue I tried one more combination (Pixel 3 + Android 11) and that worked for me.

**Comment by Dar3n1y** [comment]
hi,What can I do to use Android 7? I am M1 soc,but always the black screen
