### ISSUE TITLE
No longer needed?

### ISSUE THREAD

**Issue by wuliaolll** [google/android-emulator-m1-preview#46]
I started Android Studio 4.1.3 in macOS Big Sure 11.0.1 with new ARM cpu M1

It showed me CPU does not support VT-x, even ARM images have this issue.

When I created the AVD, the Arm64-v8a images did not worked at all, it showed me it needs to be work under the X86 system?

How could I use the AVD?

**Comment by hannesa2** [comment]
This is how I made it work https://github.com/741g/android-emulator-m1-preview/issues/10#issuecomment-773545412

**Comment by wuliaolll** [comment]
> This is how I made it work [741g/android-emulator-m1-preview#10 (comment)](https://github.com/741g/android-emulator-m1-preview/issues/10#issuecomment-773545412)

tks, It has to be the Preview version of Android Studio.
