### ISSUE TITLE
I have trouble to run older android API arm 64 images on m1, like api 25 for example is not starting . Can this project help me ?  

### ISSUE THREAD

**Issue by renetik** [google/android-emulator-m1-preview#72]
I tried api 24 and 25 and have not luck with them at all .. They don't start just opens and android don't boot up. I use comfortably 29, 30 and 31 so don't know, looks like they where not updated to support M1 or something ? I wrote so question here https://stackoverflow.com/questions/69966388/no-luck-with-running-older-android-arm-64-emulator-builds-on-m1-mac?noredirect=1#comment123680379_69966388

**Comment by radusalagean** [comment]
I need this working too. I also tried running the emulator from the command line, in hopes I'll get some descriptive error messages, unfortunately this output doesn't look much different from the API 29, 30 and 31 system images, which are all working fine.
Command: `./emulator -avd Nexus_S_API_25`
Output:
```
INFO    | Android emulator version 30.9.4.0 (build_id 7759208) (CL:N/A)
WARNING | encryption is off
INFO    | configAndStartRenderer: setting vsync to 60 hz
WARNING | cannot add library /Users/radusalagean/Library/Android/sdk/emulator/qemu/darwin-aarch64/lib64/vulkan/libvulkan.dylib: failed
WARNING | cannot add library /Users/radusalagean/Library/Android/sdk/emulator/lib64/vulkan/libvulkan.dylib: failed
WARNING | cannot add library /Users/radusalagean/Library/Android/sdk/emulator/qemu/darwin-aarch64/lib64/vulkan/libMoltenVK.dylib: failed
INFO    | added library /Users/radusalagean/Library/Android/sdk/emulator/lib64/vulkan/libMoltenVK.dylib
INFO    | Started GRPC server at 127.0.0.1:8554, security: Local
INFO    | Advertising in: /Users/radusalagean/Library/Caches/TemporaryItems/avd/running/pid_1689.ini
```

For reference, this is the output for a working API 29 image:
```
INFO    | Android emulator version 30.9.4.0 (build_id 7759208) (CL:N/A)
WARNING | unexpected system image feature string, emulator might not function correctly, please try updating the emulator.
WARNING | cannot add library /Users/radusalagean/Library/Android/sdk/emulator/qemu/darwin-aarch64/lib64/vulkan/libvulkan.dylib: failed
WARNING | cannot add library /Users/radusalagean/Library/Android/sdk/emulator/lib64/vulkan/libvulkan.dylib: failed
WARNING | cannot add library /Users/radusalagean/Library/Android/sdk/emulator/qemu/darwin-aarch64/lib64/vulkan/libMoltenVK.dylib: failed
INFO    | added library /Users/radusalagean/Library/Android/sdk/emulator/lib64/vulkan/libMoltenVK.dylib
createOrGetGlobalVkEmulation: warning: instance doesn't support external memory capabilities, picking first physical device
INFO    | configAndStartRenderer: setting vsync to 60 hz
INFO    | Started GRPC server at 127.0.0.1:8554, security: Local
INFO    | Advertising in: /Users/radusalagean/Library/Caches/TemporaryItems/avd/running/pid_1724.ini
INFO    | Warning: Failed to get QCocoaScreen for NSObject(0x0) ((null):0, (null))
```

Forgot to mention, I'm using the emulator + system images that are offered from the GUI SDK Manager inside Android Studio, not the outdated preview emulator from this github repo.

**Comment by cryptoAlgorithm** [comment]
Hi, im having the same issue here. I need to test my app on older API versions to verify functionality, but it appears that older API images simply crash on startup. ![](https://cdn.discordapp.com/attachments/867391711507513344/915164270742867998/Screenshot_2021-11-30_at_4.55.59_PM.png)

**Comment by arjun1194** [comment]
I have the same issue, did anyone find anything yet ?

**Comment by demoh2019** [comment]
I have the same issue

**Comment by arjun1194** [comment]
i was able to run default android images without google apis in the m1 emulator but  not the ones with Google APIs

**Comment by renetik** [comment]
They are working fine now for me, google fixed ti
